# Generated by Django 5.0.6 on 2024-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='violations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Суть')),
                ('photo', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.DeleteModel(
            name='Artickles',
        ),
    ]
